### ISSUE TITLE
the display strach

### ISSUE THREAD

**Issue by klokoleva** [OmarElGabry/Hashtegny#5]
hi Omar,

the images from social main-post have strach images.
how to make the width used the percent (%) or decrease the amount for a row? 

thanks

**Comment by OmarElgabry** [comment]
Hello,

You have two options here. Both ways allow you to control how many posts will be displayed in each row for different screen sizes.

**1. Using `percentPosition`**
Use `percentPosition` instead of `isFitWidth`. But, as I know, this option won't center your posts. You may play around and find if it's possible to center the posts or not, kindly check the [documentation](http://masonry.desandro.com/options.html).

``` js
// In hashtegny.js
var _options = {itemSelector: '.main-post', gutter: 10, percentPosition: true};
```

``` css
/* In main.grid.css */
.main-post {
    width: 20%;
}
@media screen and (max-width: 1024px) {
    .main-post{
        width: 40%;
    }
}
@media screen and (max-width: 480px) {
    .main-post{
        width: 100%;
    }
}
```

**2. Using `isFitWidth`(Default)**
Just use the default behavior and change the width of the post. This option will allow you to center your posts.

``` js
// In hashtegny.js
var _options = {itemSelector: '.main-post', gutter: 10, isFitWidth: true};
```

``` css
/* In main.grid.css */
.main-post {
    width: 400px;
}
@media screen and (max-width: 1024px) {
    .main-post{
        width: 300px;
    }
}
@media screen and (max-width: 480px) {
    .main-post{
        width: 280px;
    }
}
```
